AllCops:
  TargetRubyVersion: 2.5

  Exclude:
    - vendor/**/*
    - bin/**/*
    - node_modules/**/*
    - db/schema.rb

Rails:
  Enabled: true

Layout/AlignArray:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/BlockDelimiters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/GlobalVars:
  Enabled: true
  AllowedVariables:
    - '$redis'
