version: '3'
services:
  web:
    build: .
    command: bash -lc "(rm -rf tmp/pids/ || true) && yarn install && bundle exec foreman start -f Procfile.development"
    hostname: helios2-dev
    tty: true
    stdin_open: true
    volumes:
      - .:/helios:delegated
      - /helios/secure
      - /helios/tmp
    ports:
      - "5000:5000"
      - "3035:3035"
    depends_on:
      - redis
    environment:
      - RAILS_ENV=development
      - RACK_ENV=development
      - REDIS_URL=redis://redis:6379/1
  redis:
    image: redis:4.0
    ports: 
      - "6379:6379"
