version: 2
jobs:
  build-phoenix:
    docker:
       - image: cimg/elixir:1.13.3
       - image: redis
       - image: cimg/postgres:14.1
         environment:
           POSTGRES_USER: postgres
           POSTGRES_PASSWORD: postgres
           POSTGRES_DB: helios_test

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Elixir Formatting
          command: |
            cd server-phoenix && mix local.hex --force && mix deps.get && mix format --check-formatted

      - run:
          name: Unit Test
          command: |
            cd server-phoenix && mix local.rebar --force && mix test

  build-react:
    docker:
      # specify the version you desire here
       - image: cimg/node:16.14.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - yarn-cache-{{ checksum "client-react/yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - yarn-cache-

      - run:
          name: install yarn dependencies
          command: |
            cd client-react && yarn install

      - save_cache:
          paths:
            - ~/.yarn-cache
          key: yarn-cache-{{ checksum "client-react/yarn.lock" }}

      - run: cd client-react && yarn run prettier:check
      - run: cd client-react && yarn run lint
      - run: cd client-react && yarn run test

workflows:
  version: 2
  build:
    jobs:
      - build-phoenix
      - build-react

